return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 5,
  nextobjectid = 46,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 2,
          name = "hi",
          type = "",
          shape = "text",
          x = 37.6276,
          y = 34.1667,
          width = 94.08,
          height = 17,
          rotation = 0,
          visible = true,
          text = "move with wasd or arrow keys",
          wrap = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "text",
          x = 1102.96,
          y = 312.833,
          width = 82.0781,
          height = 17,
          rotation = 0,
          visible = true,
          text = "hit 'space' to create a platform",
          wrap = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "Object Layer 2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 18,
          y = 94,
          width = 460.667,
          height = 415.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 481.333,
          y = 113.333,
          width = 29.3333,
          height = 397.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512.667,
          y = 128.667,
          width = 30,
          height = 383.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 545.333,
          y = 145.333,
          width = 29.3333,
          height = 366.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 159.333,
          width = 31.3333,
          height = 352.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 607.333,
          y = 176.667,
          width = 32.6667,
          height = 336,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640.667,
          y = 192,
          width = 31.3333,
          height = 320.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672.667,
          y = 208,
          width = 30.6667,
          height = 304,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 703.333,
          y = 224,
          width = 33.3333,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 737.333,
          y = 240,
          width = 30.6667,
          height = 272.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768.667,
          y = 255.333,
          width = 30.6667,
          height = 256.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 799.333,
          y = 272,
          width = 33.3333,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832.667,
          y = 288,
          width = 30.6667,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 303.333,
          width = 32,
          height = 208.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 895.333,
          y = 320,
          width = 32,
          height = 191.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 927.333,
          y = 336,
          width = 30.6667,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 959.333,
          y = 353.333,
          width = 30.6667,
          height = 157.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 989.333,
          y = 367.333,
          width = 34.6667,
          height = 143.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 384.667,
          width = 224,
          height = 126.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1370,
          y = 236,
          width = 222.667,
          height = 77.3333,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Object Layer 3",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 32,
          name = "",
          type = "spawn",
          shape = "point",
          x = 93,
          y = 80,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["count"] = 4
          }
        },
        {
          id = 45,
          name = "",
          type = "bananna",
          shape = "point",
          x = 1484,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
